### ISSUE TITLE
Attribute error: 

### ISSUE THREAD

**Issue by sadavarti** [RobinDavid/LSB-Steganography#10]
I am trying to hide image using function "hideImage()", and it is raising an attribute error.

>  File "./main.py", line 64, in <module>
>    1:hideText(),
>  File "./main.py", line 16, in hideText
>   steg = LSBSteg(carrier)
> File "/home/sada_varti/Desktop/Project/stegano.py", line 16, in __init__
>    self.nbchannels = im.channels
>AttributeError: 'cv.iplimage' object has no attribute 'channels'

My opencv version is : 2.0.0

**Comment by Gonzalliz** [comment]
I thinks you are using open cv version 3X. Then there's no attribute called width, height or channel. Instead use im.shape which returns all 3 attrbutes.
I found the solution through this
[http://stackoverflow.com/questions/19098104/python-opencv2-cv2-wrapper-get-image-size](url)

**Comment by RobinDavid** [comment]
I fixed everything, by updating to cv2
