### ISSUE TITLE
ImageFilledException

### ISSUE THREAD

**Issue by MaxToyberman** [RobinDavid/LSB-Steganography#12]
what does it mean ? Is there noise i need to clean ?

**Comment by Gonzalliz** [comment]
Exception: (<class '__main__.SteganographyException'>, 'Image filled')

I too experienced the same issue. Is there any limitation of image size?

**Comment by MaxToyberman** [comment]
@Gonzalliz  did you manage to solve this ?

**Comment by Gonzalliz** [comment]
@MaxToyberman Yes, the problem was with image formats. I earlier used 'jpg' images. But I gave 'png' images then it worked fine for me. But the final recovered image is a crap, it's not the same image that we passed to hide. But the earlier exception is gone and all the output files are made.

**Comment by RobinDavid** [comment]
ImageFilled is meant to occur when the carrier is not big enough to hold all the data to embed.
