### ISSUE TITLE
Can't round-trip

### ISSUE THREAD

**Issue by judebert** [RobinDavid/LSB-Steganography#7]
I downloaded the "disaster girl" meme, created a "test.txt" file with all-text contents, and invoked:
`LSBSteg.py -image disaster-girl.jpg -binary test.txt -out disaster-steg.jpg`
I then attempted to retrieve the steganographically hidden txt:
`LSBSteg.py -steg-image disaster-steg.jpg -out test-round.txt`
I received an OverflowError:

> Traceback (most recent call last):
>   File "./LSBSteg.py", line 242, in <module>
>     main(av)
>   File "./LSBSteg.py", line 236, in main
>     binary_steg_reveal(args.steg_image, args.out)
>   File "./LSBSteg.py", line 212, in binary_steg_reveal
>     bin = steg.unhideBin()
>   File "./LSBSteg.py", line 194, in unhideBin
>     for i in range(l):
> OverflowError: range() result has too many items

**Comment by sugusrojo** [comment]
Same error here:

`python LSBSteg.py -steg-image ch.png -out imagen.png
Traceback (most recent call last):
  File "LSBSteg.py", line 242, in <module>
    main(av)
  File "LSBSteg.py", line 236, in main
    binary_steg_reveal(args.steg_image, args.out)
  File "LSBSteg.py", line 212, in binary_steg_reveal
    bin = steg.unhideBin()
  File "LSBSteg.py", line 194, in unhideBin
    for i in range(l):
OverflowError: range() result has too many items
`

**Comment by judebert** [comment]
I never managed to resolve it. I had to abandon my project.

**Comment by RobinDavid** [comment]
Can you provide the image and the file to embed, so that I can reproduce the issue ?
