### ISSUE TITLE
Save result to jpeg file fail to get unhide text

### ISSUE THREAD

**Issue by honeytidy** [RobinDavid/LSB-Steganography#8]
This is my code: 
`from LSBSteg import LSBSteg
import cv
# Hide

str = "Hello World"
carrier = cv.LoadImage("1472282893350.jpg")
steg = LSBSteg(carrier)
steg.hideText(str)
steg.saveImage("result.jpg") # change to result.png will be ok
# Unhide

im = cv.LoadImage("result.jpg") # change to result.png will be ok
steg = LSBSteg(im)
print "Text value:",steg.unhideText()
`
I get result like that:
![image](https://cloud.githubusercontent.com/assets/1021165/19270758/28ce6ff0-8ff4-11e6-8551-23d0e9463c03.png)

But if change `result.jpg` to `result.png` will be fine.

**Comment by RobinDavid** [comment]
JPEG performs data compression so bits get lost in that process. You  cannot control the compression so you have to take format without compression.
