### ISSUE TITLE
How to hide a text "n" times?

### ISSUE THREAD

**Issue by amsr9** [RobinDavid/LSB-Steganography#9]
Hi, I really like this repository, thank you so much Robin for developing it.
I would like to hide a piece of short text (<100 bytes) "n" times in random places within the carrier.  I tried to follow the functions but I got lost and couldn't figure out.

Any tips please?

**Comment by RobinDavid** [comment]
The easier way is to call `next_slot` an arbitrary number of time, then calling `encode_text` to hide your text and repeating the process "n" times to hide it again.
